import {useCallback,useEffect,useState} from "react";
import {CirclePlus,Pencil,Power,Search,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {cambiarEstadoCaracteristica,crearCaracteristica,editarCaracteristica,listarCaracteristicas,obtenerCatalogosCaracteristica,type CaracteristicaMantenimiento,type MetodoEnsayoMantenimiento,type TipoCaracteristicaMantenimiento} from "./api";

type Filtro="todos"|"activos"|"inactivos";
export default function CaracteristicasMantenimientoPage(){
 const [items,setItems]=useState<CaracteristicaMantenimiento[]>([]),[tipos,setTipos]=useState<TipoCaracteristicaMantenimiento[]>([]),[metodos,setMetodos]=useState<MetodoEnsayoMantenimiento[]>([]);
 const [busqueda,setBusqueda]=useState(""),[tipoFiltro,setTipoFiltro]=useState(""),[filtro,setFiltro]=useState<Filtro>("todos"),[cargando,setCargando]=useState(true);
 const [editando,setEditando]=useState<CaracteristicaMantenimiento|null|undefined>(undefined),[descripcion,setDescripcion]=useState(""),[unidad,setUnidad]=useState(""),[tipoId,setTipoId]=useState(""),[metodoId,setMetodoId]=useState(""),[metodoBusqueda,setMetodoBusqueda]=useState(""),[metodoAbierto,setMetodoAbierto]=useState(false),[guardando,setGuardando]=useState(false),[error,setError]=useState("");
 const cargar=useCallback(async()=>{setCargando(true);try{setItems(await listarCaracteristicas({busqueda:busqueda.trim()||undefined,tipoCaractId:tipoFiltro?Number(tipoFiltro):undefined,estado:filtro==="todos"?undefined:filtro==="activos"}))}finally{setCargando(false)}},[busqueda,tipoFiltro,filtro]);
 useEffect(()=>{obtenerCatalogosCaracteristica().then(x=>{setTipos(x.tiposCaracteristica);setMetodos(x.metodosEnsayo)})},[]);
 useEffect(()=>{const t=window.setTimeout(cargar,250);return()=>window.clearTimeout(t)},[cargar]);
 const abrirNuevo=()=>{setEditando(null);setDescripcion("");setUnidad("");setTipoId("");setMetodoId("");setMetodoBusqueda("");setMetodoAbierto(false);setError("")};
 const abrirEditar=(x:CaracteristicaMantenimiento)=>{setEditando(x);setDescripcion(x.caracteristicaDescripcion);setUnidad(x.caracteristicaUnidadDeMedida??"");setTipoId(String(x.tipoCaractId));setMetodoId(x.metEnsayoId?String(x.metEnsayoId):"");setMetodoBusqueda(x.metEnsayoDescripcion??"");setMetodoAbierto(false);setError("")};
 const cerrar=()=>setEditando(undefined);
 const guardar=async()=>{if(!descripcion.trim()){setError("La descripción es obligatoria.");return}if(!tipoId){setError("El tipo de característica es obligatorio.");return}if(!metodoId){setError("El método de ensayo es obligatorio.");return}setGuardando(true);setError("");try{const req={caracteristicaDescripcion:descripcion.trim(),caracteristicaUnidadDeMedida:unidad.trim()||null,tipoCaractId:Number(tipoId),metEnsayoId:Number(metodoId)};if(editando)await editarCaracteristica(editando.caracteristicaId,req);else await crearCaracteristica(req);cerrar();await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar la característica.")}finally{setGuardando(false)}};
 const estado=async(x:CaracteristicaMantenimiento)=>{if(!window.confirm(`¿Deseas ${x.estado?"inactivar":"activar"} “${x.caracteristicaDescripcion}”?`))return;await cambiarEstadoCaracteristica(x.caracteristicaId,!x.estado);await cargar()};
 return <div className="mx-auto w-full max-w-[1500px] space-y-6 px-6 py-6 xl:px-8">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--text-secondary)]">Mantenimientos</p><h1 className="text-2xl font-semibold">Maestro de Características</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Administra las características disponibles para las especificaciones técnicas.</p></div><Button onClick={abrirNuevo}><CirclePlus/>Nueva característica</Button></div>
  <Card><CardContent className="p-6"><div className="flex flex-wrap gap-3"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Buscar característica, unidad, tipo o método..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><select className="h-10 rounded-md border bg-white px-3 text-sm" value={tipoFiltro} onChange={e=>setTipoFiltro(e.target.value)}><option value="">Todos los tipos</option>{tipos.map(x=><option key={x.tipoCaractId} value={x.tipoCaractId}>{x.tipoCaractDescripcion}</option>)}</select><select className="h-10 rounded-md border bg-white px-3 text-sm" value={filtro} onChange={e=>setFiltro(e.target.value as Filtro)}><option value="todos">Todos</option><option value="activos">Activos</option><option value="inactivos">Inactivos</option></select></div></CardContent></Card>
  <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Característica</th><th>Tipo</th><th>Unidad</th><th>Método de ensayo</th><th>Estado</th><th>Uso en ET</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>
   {cargando?<tr><td colSpan={7} className="px-5 py-10 text-center text-[var(--text-secondary)]">Cargando características...</td></tr>:items.length===0?<tr><td colSpan={7} className="px-5 py-10 text-center text-[var(--text-secondary)]">No se encontraron características.</td></tr>:items.map(x=><tr key={x.caracteristicaId} className="border-t"><td className="px-5 py-3 font-medium">{x.caracteristicaDescripcion}</td><td>{x.tipoCaractDescripcion}</td><td>{x.caracteristicaUnidadDeMedida??"—"}</td><td>{x.metEnsayoDescripcion??"—"}</td><td><span className={`rounded-full px-2 py-1 text-xs font-medium ${x.estado?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{x.estado?"Activo":"Inactivo"}</span></td><td>{x.tieneUso?"En uso":"Sin uso"}</td><td className="px-5 text-right"><div className="flex justify-end gap-2"><Button size="icon-sm" variant="outline" title="Editar" onClick={()=>abrirEditar(x)}><Pencil/></Button><Button size="icon-sm" variant="outline" title={x.estado?"Inactivar":"Activar"} onClick={()=>estado(x)}><Power/></Button></div></td></tr>)}
  </tbody></table></div></CardContent></Card>
  {editando!==undefined&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-xl rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">{editando?"Editar característica":"Nueva característica"}</h2><p className="text-xs text-[var(--text-secondary)]">Define la combinación reutilizable que estará disponible en las ET.</p></div><button onClick={cerrar}><X className="h-5 w-5"/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="block text-sm font-medium sm:col-span-2">Característica<Input className="mt-1" maxLength={200} value={descripcion} onChange={e=>setDescripcion(e.target.value)} placeholder="Ej. pH, Humedad, Color"/></label><label className="block text-sm font-medium">Tipo<select className="mt-1 h-10 w-full rounded-md border bg-white px-3 text-sm" value={tipoId} onChange={e=>setTipoId(e.target.value)}><option value="">Seleccionar...</option>{tipos.map(x=><option key={x.tipoCaractId} value={x.tipoCaractId}>{x.tipoCaractDescripcion}</option>)}</select></label><label className="block text-sm font-medium">Unidad de medida<Input className="mt-1" maxLength={50} value={unidad} onChange={e=>setUnidad(e.target.value)} placeholder="Ej. %, UFC / g, N.A."/></label><label className="relative block text-sm font-medium sm:col-span-2">Método de ensayo<Input className="mt-1" value={metodoBusqueda} onFocus={()=>setMetodoAbierto(true)} onChange={e=>{setMetodoBusqueda(e.target.value);setMetodoId("");setMetodoAbierto(true)}} placeholder="Escribe para buscar, ej. OVOPE-CA-I-029" autoComplete="off"/>{metodoAbierto&&<div className="absolute z-[70] mt-1 max-h-56 w-full overflow-y-auto rounded-md border bg-white shadow-lg">{metodos.filter(x=>x.metEnsayoDescripcion.toLowerCase().includes(metodoBusqueda.trim().toLowerCase())).length===0?<div className="px-3 py-2 text-sm text-[var(--text-secondary)]">No se encontraron métodos.</div>:metodos.filter(x=>x.metEnsayoDescripcion.toLowerCase().includes(metodoBusqueda.trim().toLowerCase())).map(x=><button key={x.metEnsayoId} type="button" className="block w-full px-3 py-2 text-left text-sm hover:bg-slate-100" onMouseDown={e=>e.preventDefault()} onClick={()=>{setMetodoId(String(x.metEnsayoId));setMetodoBusqueda(x.metEnsayoDescripcion);setMetodoAbierto(false)}}>{x.metEnsayoDescripcion}</button>)}</div>}</label>{error&&<div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 sm:col-span-2">{error}</div>}</div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={cerrar}>Cancelar</Button><Button disabled={guardando} onClick={guardar}>{guardando?"Guardando...":"Guardar"}</Button></div></div></div>}
 </div>
}
