import {useCallback,useEffect,useState} from "react";
import {CirclePlus,Pencil,Power,Search,Trash2,X} from "lucide-react";
import {Button} from "@/components/ui/button";import {Card,CardContent} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {cambiarEstadoCargo,crearCargo,editarCargo,eliminarCargo,listarCargos,type CargoMaestro} from "./api";
type Filtro="todos"|"activos"|"inactivos";
export default function CargosMantenimientoPage(){
 const [items,setItems]=useState<CargoMaestro[]>([]),[busqueda,setBusqueda]=useState(""),[filtro,setFiltro]=useState<Filtro>("todos"),[cargando,setCargando]=useState(true);
 const [editando,setEditando]=useState<CargoMaestro|null|undefined>(undefined),[descripcion,setDescripcion]=useState(""),[guardando,setGuardando]=useState(false),[error,setError]=useState("");
 const cargar=useCallback(async()=>{setCargando(true);try{setItems(await listarCargos({busqueda:busqueda.trim()||undefined,estado:filtro==="todos"?undefined:filtro==="activos"}))}finally{setCargando(false)}},[busqueda,filtro]);
 useEffect(()=>{const t=setTimeout(cargar,250);return()=>clearTimeout(t)},[cargar]);
 const guardar=async()=>{if(!descripcion.trim())return setError("La descripción es obligatoria.");setGuardando(true);setError("");try{editando?await editarCargo(editando.cargoId,{cargoDescripcion:descripcion.trim()}):await crearCargo({cargoDescripcion:descripcion.trim()});setEditando(undefined);await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.")}finally{setGuardando(false)}};
 return <div className="mx-auto w-full max-w-[1500px] space-y-6 px-6 py-6 xl:px-8">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--text-secondary)]">Mantenimientos</p><h1 className="text-2xl font-semibold">Maestro de Cargos</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Administra los cargos disponibles para los responsables de documentos.</p></div><Button onClick={()=>{setEditando(null);setDescripcion("");setError("")}}><CirclePlus/>Nuevo cargo</Button></div>
  <Card><CardContent className="p-6"><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Buscar cargo..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><select className="h-10 rounded-md border bg-white px-3 text-sm" value={filtro} onChange={e=>setFiltro(e.target.value as Filtro)}><option value="todos">Todos</option><option value="activos">Activos</option><option value="inactivos">Inactivos</option></select></div></CardContent></Card>
  <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Cargo</th><th>Estado</th><th>Responsables</th><th>Uso histórico</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>{cargando?<tr><td colSpan={5} className="p-10 text-center">Cargando...</td></tr>:items.map(x=><tr key={x.cargoId} className="border-t"><td className="px-5 py-3 font-medium">{x.cargoDescripcion}</td><td>{x.estado?"Activo":"Inactivo"}</td><td>{x.cantidadResponsables}</td><td>{x.tieneUso?"En uso":"Sin uso"}</td><td className="px-5 text-right"><div className="flex justify-end gap-2"><Button size="icon-sm" variant="outline" onClick={()=>{setEditando(x);setDescripcion(x.cargoDescripcion);setError("")}}><Pencil/></Button>{!x.tieneUso&&<Button size="icon-sm" variant="outline" title="Eliminar cargo" className="text-red-600 hover:bg-red-50 hover:text-red-700" onClick={async()=>{if(confirm(`¿Eliminar definitivamente el cargo “${x.cargoDescripcion}”? Esta acción solo está permitida porque no tiene uso histórico.`)){try{await eliminarCargo(x.cargoId);await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo eliminar.")}}}}><Trash2/></Button>}<Button size="icon-sm" variant="outline" onClick={async()=>{if(confirm(`¿Deseas ${x.estado?"inactivar":"activar"} “${x.cargoDescripcion}”?`)){await cambiarEstadoCargo(x.cargoId,!x.estado);await cargar()}}}><Power/></Button></div></td></tr>)}</tbody></table></div></CardContent></Card>
  {editando!==undefined&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-lg rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-semibold">{editando?"Editar":"Nuevo"} cargo</h2><button onClick={()=>setEditando(undefined)}><X/></button></div><div className="p-5"><label className="text-sm font-medium">Descripción<Input className="mt-1" maxLength={150} value={descripcion} onChange={e=>setDescripcion(e.target.value)}/></label>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={()=>setEditando(undefined)}>Cancelar</Button><Button disabled={guardando} onClick={guardar}>{guardando?"Guardando...":"Guardar"}</Button></div></div></div>}
 </div>
}