import {useCallback,useEffect,useState} from "react";
import {CirclePlus,Pencil,Power,Search,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {cambiarEstadoIngrediente,crearIngrediente,editarIngrediente,listarIngredientes,type IngredienteMantenimiento} from "./api";

type Filtro="todos"|"activos"|"inactivos";
export default function IngredientesMantenimientoPage(){
 const [items,setItems]=useState<IngredienteMantenimiento[]>([]),[busqueda,setBusqueda]=useState(""),[filtro,setFiltro]=useState<Filtro>("todos"),[cargando,setCargando]=useState(true);
 const [editando,setEditando]=useState<IngredienteMantenimiento|null|undefined>(undefined),[descripcion,setDescripcion]=useState(""),[guardando,setGuardando]=useState(false),[error,setError]=useState("");
 const cargar=useCallback(async()=>{setCargando(true);try{setItems(await listarIngredientes({busqueda:busqueda.trim()||undefined,estado:filtro==="todos"?undefined:filtro==="activos"}))}finally{setCargando(false)}},[busqueda,filtro]);
 useEffect(()=>{const t=window.setTimeout(cargar,250);return()=>window.clearTimeout(t)},[cargar]);
 const abrirNuevo=()=>{setEditando(null);setDescripcion("");setError("")};
 const abrirEditar=(x:IngredienteMantenimiento)=>{setEditando(x);setDescripcion(x.ingredienteDescripcion);setError("")};
 const cerrar=()=>setEditando(undefined);
 const guardar=async()=>{if(!descripcion.trim()){setError("La descripción es obligatoria.");return}setGuardando(true);setError("");try{const req={ingredienteDescripcion:descripcion.trim()};if(editando)await editarIngrediente(editando.ingredienteId,req);else await crearIngrediente(req);cerrar();await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar el ingrediente.")}finally{setGuardando(false)}};
 const estado=async(x:IngredienteMantenimiento)=>{if(!window.confirm(`¿Deseas ${x.estado?"inactivar":"activar"} “${x.ingredienteDescripcion}”?`))return;await cambiarEstadoIngrediente(x.ingredienteId,!x.estado);await cargar()};
 return <div className="mx-auto w-full max-w-[1500px] space-y-6 px-6 py-6 xl:px-8">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--text-secondary)]">Mantenimientos</p><h1 className="text-2xl font-semibold">Maestro de Ingredientes</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Administra los ingredientes disponibles para las especificaciones técnicas.</p></div><Button onClick={abrirNuevo}><CirclePlus/>Nuevo ingrediente</Button></div>
  <Card><CardContent className="p-6"><div className="flex flex-wrap gap-3"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Buscar por ingrediente..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><select className="h-10 rounded-md border bg-white px-3 text-sm" value={filtro} onChange={e=>setFiltro(e.target.value as Filtro)}><option value="todos">Todos</option><option value="activos">Activos</option><option value="inactivos">Inactivos</option></select></div></CardContent></Card>
  <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Ingrediente</th><th>Estado</th><th>Uso en ET</th><th>Última actualización</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>
   {cargando?<tr><td colSpan={5} className="px-5 py-10 text-center text-[var(--text-secondary)]">Cargando ingredientes...</td></tr>:items.length===0?<tr><td colSpan={6} className="px-5 py-10 text-center text-[var(--text-secondary)]">No se encontraron ingredientes.</td></tr>:items.map(x=><tr key={x.ingredienteId} className="border-t"><td className="px-5 py-3 font-medium">{x.ingredienteDescripcion}</td><td><span className={`rounded-full px-2 py-1 text-xs font-medium ${x.estado?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{x.estado?"Activo":"Inactivo"}</span></td><td>{x.tieneUso?"En uso":"Sin uso"}</td><td>{x.audFechaActualizacion?new Date(x.audFechaActualizacion).toLocaleString():"—"}</td><td className="px-5 text-right"><div className="flex justify-end gap-2"><Button size="icon-sm" variant="outline" title="Editar" onClick={()=>abrirEditar(x)}><Pencil/></Button><Button size="icon-sm" variant="outline" title={x.estado?"Inactivar":"Activar"} onClick={()=>estado(x)}><Power/></Button></div></td></tr>)}
  </tbody></table></div></CardContent></Card>
  {editando!==undefined&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-lg rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">{editando?"Editar ingrediente":"Nuevo ingrediente"}</h2><p className="text-xs text-[var(--text-secondary)]">La unidad de medida se registra individualmente en cada especificación técnica.</p></div><button onClick={cerrar}><X className="h-5 w-5"/></button></div><div className="space-y-4 p-5"><label className="block text-sm font-medium">Ingrediente<Input className="mt-1" maxLength={500} value={descripcion} onChange={e=>setDescripcion(e.target.value)} placeholder="Descripción del ingrediente"/></label>{error&&<div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}</div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={cerrar}>Cancelar</Button><Button disabled={guardando} onClick={guardar}>{guardando?"Guardando...":"Guardar"}</Button></div></div></div>}
 </div>
}