import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowLeft,Check,Save} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {obtenerCatalogosEt} from "@/modules/especificaciones/api";
import {guardarCaracteristicaFt,listarCaracteristicasFt,obtenerFt} from "./api";
import type {CaracteristicaFt} from "./types";
export default function EditarFichaTecnicaPage(){
 const id=Number(useParams().versionId),nav=useNavigate(),qc=useQueryClient();
 const ft=useQuery({queryKey:["ft",id],queryFn:()=>obtenerFt(id),enabled:Number.isFinite(id)});
 const chars=useQuery({queryKey:["ft-caracteristicas",id],queryFn:()=>listarCaracteristicasFt(id),enabled:Number.isFinite(id)});
 const cats=useQuery({queryKey:["catalogos-et"],queryFn:obtenerCatalogosEt});
 const [editando,setEditando]=useState<Record<number,CaracteristicaFt>>({});
 const filas=useMemo(()=>chars.data??[],[chars.data]);
 const guardar=useMutation({mutationFn:(x:CaracteristicaFt)=>guardarCaracteristicaFt(id,{versionFtCaracteristicaId:x.versionFtCaracteristicaId,caracteristicaId:x.caracteristicaId,tipoCriterioId:x.tipoCriterioId,valorCuantitativoInicial:x.valorCuantitativoInicial,valorCuantitativoFinal:x.valorCuantitativoFinal,valorCuantitativoIgual:x.valorCuantitativoIgual,valorCualitativo:x.valorCualitativo,unidadDeMedida:x.unidadDeMedida,imprimeCertificado:x.imprimeCertificado,obligatorioCertificado:x.obligatorioCertificado,ordenCertificado:x.imprimeCertificado?x.ordenCertificado:null}),onSuccess:(_,x)=>{setEditando(a=>{const n={...a};delete n[x.versionFtCaracteristicaId];return n});qc.invalidateQueries({queryKey:["ft-caracteristicas",id]});qc.invalidateQueries({queryKey:["fichas-tecnicas"]})}});
 const valor=(x:CaracteristicaFt)=>editando[x.versionFtCaracteristicaId]??x;
 const patch=(x:CaracteristicaFt,p:Partial<CaracteristicaFt>)=>setEditando(a=>({...a,[x.versionFtCaracteristicaId]:{...valor(x),...p}}));
 const criterio=(x:CaracteristicaFt)=>{const c=cats.data?.tiposCriterio.find(t=>t.tipoCriterioId===x.tipoCriterioId);return c?.tipoCriterio??String(x.tipoCriterioId)};
 return <PageContainer className="space-y-5">
  <div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--text-secondary)]">Gestión documental · Ficha técnica</p><h1 className="mt-1 text-2xl font-semibold">{ft.data?.productoCodigo} · {ft.data?.documentoCodigo}</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">{ft.data?.documentoDescripcionDocumento} · v{ft.data?.versionNumero} · {ft.data?.estadoVersion}</p></div><Button variant="outline" onClick={()=>nav("/documentos/fichas-tecnicas")}><ArrowLeft/>Volver</Button></div>
  <Card><CardContent className="p-5"><h2 className="font-semibold">Características de la Ficha Técnica</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Aquí se define qué parámetros de la FT pueden utilizarse en certificados. La ET continúa siendo la especificación interna de evaluación.</p></CardContent></Card>
  <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-3">Tipo</th><th className="p-3">Característica</th><th className="p-3">Criterio</th><th className="p-3">Especificación FT</th><th className="p-3">Unidad</th><th className="p-3 text-center">Imprime certificado</th><th className="p-3 text-center">Obligatorio</th><th className="p-3">Orden</th><th className="p-3"></th></tr></thead><tbody>{filas.map(base=>{const x=valor(base);const esp=x.valorCualitativo??(x.valorCuantitativoIgual!=null?String(x.valorCuantitativoIgual):[x.valorCuantitativoInicial,x.valorCuantitativoFinal].filter(v=>v!=null).join(" – "));return <tr key={base.versionFtCaracteristicaId} className="border-b last:border-0"><td className="p-3">{x.tipoCaractDescripcion}</td><td className="p-3 font-semibold">{x.caracteristicaDescripcion}</td><td className="p-3">{criterio(x)}</td><td className="p-3">{esp||"—"}</td><td className="p-3">{x.unidadDeMedida||"—"}</td><td className="p-3 text-center"><input type="checkbox" checked={x.imprimeCertificado} onChange={e=>patch(base,{imprimeCertificado:e.target.checked,obligatorioCertificado:e.target.checked?x.obligatorioCertificado:false,ordenCertificado:e.target.checked?(x.ordenCertificado??1):null})}/></td><td className="p-3 text-center"><input type="checkbox" disabled={!x.imprimeCertificado} checked={x.obligatorioCertificado} onChange={e=>patch(base,{obligatorioCertificado:e.target.checked})}/></td><td className="p-3"><input className="h-9 w-20 rounded-md border px-2" type="number" min={1} disabled={!x.imprimeCertificado} value={x.ordenCertificado??""} onChange={e=>patch(base,{ordenCertificado:e.target.value?Number(e.target.value):null})}/></td><td className="p-3"><Button size="sm" disabled={!editando[base.versionFtCaracteristicaId]||guardar.isPending} onClick={()=>guardar.mutate(x)}><Save/>Guardar</Button></td></tr>})}</tbody></table></div>{guardar.isSuccess&&<div className="flex items-center gap-2 border-t p-3 text-sm text-emerald-700"><Check size={16}/>Configuración actualizada.</div>}</CardContent></Card>
 </PageContainer>
}
