export type CrearFichaTecnicaRequest={documentoCodigo:string;documentoDescripcionDocumento:string;productoCodigo:string|null;versionNumero:number|null;versionInicioVigencia:string|null;versionReemplazaAId:number|null;versionNroPaginas:number|null;versionDescripcion:string|null;versionEtOrigenId:number|null};
export type CrearFichaTecnicaResponse={codigoResultado:number;mensaje:string;documentoId:number|null;documentoCodigo:string|null;documentoDescripcionDocumento:string|null;tipoDocumentoId:number|null;tipoDocumentoDescripcion:string|null;productoCodigo:string|null;versionId:number|null;versionNumero:number|null;estVerId:number|null;estadoVersion:string|null;versionInicioVigencia:string|null;versionReemplazaAId:number|null;versionNroPaginas:number|null;versionDescripcion:string|null;versionEtOrigenId:number|null};
export type CaracteristicaFt={versionFtCaracteristicaId:number;versionId:number;caracteristicaId:number;caracteristicaDescripcion:string;tipoCaractId:number|null;tipoCaractDescripcion:string|null;tipoCriterioId:number;valorCuantitativoInicial:number|null;valorCuantitativoFinal:number|null;valorCuantitativoIgual:number|null;valorCualitativo:string|null;unidadDeMedida:string|null;metEnsayoId:number|null;metEnsayoDescripcion:string|null;imprimeCertificado:boolean;obligatorioCertificado:boolean;ordenCertificado:number|null;estado:boolean};
export type GuardarCaracteristicaFt={versionFtCaracteristicaId:number|null;caracteristicaId:number;tipoCriterioId:number;valorCuantitativoInicial:number|null;valorCuantitativoFinal:number|null;valorCuantitativoIgual:number|null;valorCualitativo:string|null;unidadDeMedida:string|null;imprimeCertificado:boolean;obligatorioCertificado:boolean;ordenCertificado:number|null};
export type OperacionFt={codigoResultado:number;mensaje:string;versionFtCaracteristicaId?:number|null};

export type FichaTecnicaGestion={versionId:number;documentoId:number;documentoCodigo:string;documentoDescripcionDocumento:string;productoCodigo:string|null;versionNumero:number|null;versionInicioVigencia:string|null;estVerId:number;estadoVersion:string;versionNroPaginas:number|null;versionDescripcion:string|null;cantidadCaracteristicas:number;cantidadParametrosCertificables:number};

export type EliminarFichaTecnicaResponse={codigoResultado:number;mensaje:string;versionId:number};
