import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowDown,ArrowLeft,ArrowUp,Edit3,EyeOff,FileCheck2,Plus,Save,Trash2,X} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {agregarSeccionFt,guardarCaracteristicaFt,guardarSeccionFt,listarCaracteristicasFt,listarSeccionesFt,quitarSeccionFt,reordenarSeccionesFt} from "./api";
import type {CaracteristicaFt,GuardarCaracteristicaFt,SeccionFt} from "./types";

const usuario="USUARIO_WEB";
export default function FichaTecnicaPage(){
 const nav=useNavigate(),qc=useQueryClient(),{versionId}=useParams(),id=Number(versionId);
 const [seccionId,setSeccionId]=useState<number|null>(null),[editCar,setEditCar]=useState<CaracteristicaFt|null>(null),[error,setError]=useState(""),[modalSeccion,setModalSeccion]=useState(false);
 const secciones=useQuery({queryKey:["ft-secciones",id],queryFn:()=>listarSeccionesFt(id),enabled:id>0});
 const caracteristicas=useQuery({queryKey:["ft-caracteristicas",id],queryFn:()=>listarCaracteristicasFt(id),enabled:id>0});
 const refrescar=async()=>{await Promise.all([qc.invalidateQueries({queryKey:["ft-secciones",id]}),qc.invalidateQueries({queryKey:["ft-caracteristicas",id]})])};
 useEffect(()=>{if(!seccionId&&secciones.data?.length)setSeccionId([...secciones.data].sort((a,b)=>a.orden-b.orden)[0].versionFtSeccionId)},[secciones.data,seccionId]);
 const saveSec=useMutation({mutationFn:(s:SeccionFt)=>guardarSeccionFt(id,s.versionFtSeccionId,{titulo:s.titulo,contenido:s.contenido,visible:s.visible,usuario}),onSuccess:async()=>{setError("");await refrescar()},onError:(e:Error)=>setError(e.message)});
 const delSec=useMutation({mutationFn:(sid:number)=>quitarSeccionFt(id,sid),onSuccess:async()=>{setError("");setSeccionId(null);await refrescar()},onError:(e:Error)=>setError(e.message)});
 const addSec=useMutation({mutationFn:(x:{titulo:string;tipoContenido:"TEXTO"|"LISTA"|"TABLA"})=>agregarSeccionFt(id,{...x,orden:null,usuario}),onSuccess:async()=>{setModalSeccion(false);await refrescar()},onError:(e:Error)=>setError(e.message)});
 const saveCar=useMutation({mutationFn:({x,r}:{x:CaracteristicaFt;r:GuardarCaracteristicaFt})=>guardarCaracteristicaFt(id,x.versionFtCaracteristicaId,r),onSuccess:async()=>{setEditCar(null);setError("");await refrescar()},onError:(e:Error)=>setError(e.message)});
 const mover=async(s:SeccionFt,dir:-1|1)=>{const lista=[...(secciones.data??[])].sort((a,b)=>a.orden-b.orden),i=lista.findIndex(x=>x.versionFtSeccionId===s.versionFtSeccionId),j=i+dir;if(j<0||j>=lista.length)return;[lista[i],lista[j]]=[lista[j],lista[i]];try{await reordenarSeccionesFt(id,{secciones:lista.map((x,k)=>({versionFtSeccionId:x.versionFtSeccionId,orden:k+1})),usuario});await refrescar()}catch(e){setError(e instanceof Error?e.message:"No se pudo reordenar.")}};
 if(secciones.isLoading||caracteristicas.isLoading)return <PageContainer><div className="py-16 text-center">Cargando Ficha Técnica...</div></PageContainer>;
 if(secciones.isError||caracteristicas.isError)return <PageContainer><div className="py-16 text-center text-red-600">No se pudo cargar la Ficha Técnica.</div></PageContainer>;
 const lista=[...(secciones.data??[])].sort((a,b)=>a.orden-b.orden),activa=lista.find(x=>x.versionFtSeccionId===seccionId)??lista[0];
 const cars=[...(caracteristicas.data??[])].sort((a,b)=>(a.ordenTecnico??999)-(b.ordenTecnico??999));
 return <PageContainer className="space-y-4">
  <Button variant="ghost" size="sm" className="-ml-2" onClick={()=>nav("/documentos/fichas-tecnicas")}><ArrowLeft/>Volver a fichas técnicas</Button>
  <Card className="border-t-4 border-t-slate-800"><CardContent className="flex flex-wrap items-center justify-between gap-4 p-6"><div><div className="flex items-center gap-2"><FileCheck2 className="size-5"/><Badge variant="outline">FT</Badge></div><h1 className="mt-3 text-2xl font-semibold">Ficha Técnica · Versión {id}</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Estructura documental y configuración independiente para certificado.</p></div><div className="text-right"><p className="text-xs text-[var(--text-secondary)]">Características</p><p className="text-2xl font-semibold">{cars.length}</p></div></CardContent></Card>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
   <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">Estructura FT</h2><p className="text-xs text-[var(--text-secondary)]">{lista.length} secciones</p></div><Button size="icon-sm" variant="outline" onClick={()=>setModalSeccion(true)}><Plus/></Button></div><div className="p-2">{lista.map((s,i)=><button key={s.versionFtSeccionId} onClick={()=>setSeccionId(s.versionFtSeccionId)} className={"mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm "+(activa?.versionFtSeccionId===s.versionFtSeccionId?"bg-slate-900 text-white":"hover:bg-slate-50")}><span className="w-5 text-xs opacity-60">{s.orden}</span><span className="min-w-0 flex-1 truncate">{s.titulo}</span>{!s.visible&&<EyeOff className="size-3.5"/>}<span className="flex gap-1" onClick={e=>e.stopPropagation()}><ArrowUp className={"size-3.5 cursor-pointer "+(i===0?"opacity-30":"")} onClick={()=>mover(s,-1)}/><ArrowDown className={"size-3.5 cursor-pointer "+(i===lista.length-1?"opacity-30":"")} onClick={()=>mover(s,1)}/></span></button>)}</div></CardContent></Card>
   <div className="min-w-0">{activa?.codigo==="CARACTERISTICAS"?<Caracteristicas items={cars} onEditar={setEditCar}/>:activa?<SeccionEditor seccion={activa} saving={saveSec.isPending} deleting={delSec.isPending} onGuardar={s=>saveSec.mutate(s)} onEliminar={s=>{if(confirm(`¿Retirar ${s.titulo} de esta FT?`))delSec.mutate(s.versionFtSeccionId)}}/>:<Card><CardContent className="p-8 text-center text-sm text-[var(--text-secondary)]">Sin secciones.</CardContent></Card>}</div>
  </div>
  {editCar&&<CaracteristicaModal item={editCar} busy={saveCar.isPending} onClose={()=>setEditCar(null)} onSave={r=>saveCar.mutate({x:editCar,r})}/>}
  {modalSeccion&&<NuevaSeccionModal busy={addSec.isPending} onClose={()=>setModalSeccion(false)} onSave={(titulo,tipoContenido)=>addSec.mutate({titulo,tipoContenido})}/>}
 </PageContainer>
}

function SeccionEditor({seccion,saving,deleting,onGuardar,onEliminar}:{seccion:SeccionFt;saving:boolean;deleting:boolean;onGuardar:(s:SeccionFt)=>void;onEliminar:(s:SeccionFt)=>void}){
 const [s,setS]=useState(seccion);useEffect(()=>setS(seccion),[seccion]);
 return <Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase text-[var(--text-secondary)]">{s.tipoContenido}</p><Input className="mt-2 max-w-xl font-semibold" value={s.titulo} onChange={e=>setS({...s,titulo:e.target.value})}/></div><div className="flex gap-2"><label className="flex items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={s.visible} onChange={e=>setS({...s,visible:e.target.checked})}/>Visible</label>{!s.esSistema&&<Button variant="destructive" disabled={deleting} onClick={()=>onEliminar(s)}><Trash2/>Quitar</Button>}</div></div><textarea className="min-h-72 w-full resize-y rounded-lg border bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-slate-200" value={s.contenido??""} onChange={e=>setS({...s,contenido:e.target.value})} placeholder={s.tipoContenido==="LISTA"?"Ingrese un elemento por línea...":"Ingrese el contenido de esta sección..."}/><div className="flex justify-end"><Button disabled={saving||!s.titulo.trim()} onClick={()=>onGuardar(s)}><Save/>{saving?"Guardando...":"Guardar sección"}</Button></div></CardContent></Card>
}

function Caracteristicas({items,onEditar}:{items:CaracteristicaFt[];onEditar:(x:CaracteristicaFt)=>void}){
 const grupos=useMemo(()=>{const m=new Map<string,CaracteristicaFt[]>();for(const x of items){const k=x.tipoCaracteristicaDescripcion??"OTRAS";m.set(k,[...(m.get(k)??[]),x])}return [...m.entries()]},[items]);
 return <div className="space-y-4">{grupos.map(([tipo,a])=><Card key={tipo}><CardContent className="p-0"><div className="border-b px-5 py-4"><h2 className="font-semibold">{cap(tipo)}</h2><p className="text-xs text-[var(--text-secondary)]">{a.length} características · orden técnico preservado desde ET</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Orden</th><th>Característica</th><th>Criterio FT</th><th>Unidad</th><th>Método</th><th>Certificado</th><th className="px-5 text-right">Acción</th></tr></thead><tbody>{a.map(x=><tr key={x.versionFtCaracteristicaId} className="border-t"><td className="px-5 py-3">{x.ordenTecnico??"—"}</td><td><b>{x.caracteristicaDescripcion}</b><div className="text-xs text-[var(--text-secondary)]">{x.faseCodigo??"Sin fase"}</div></td><td>{x.criterioMostrar??"—"}</td><td>{x.unidadDeMedida??x.unidadCatalogo??"N.A."}</td><td>{x.metodoEnsayoDescripcion??"N.A."}</td><td>{x.imprimeCertificado?<span className="font-medium text-emerald-700">Sí · orden {x.ordenCertificado??"—"}{x.obligatorioCertificado?" · obligatorio":""}</span>:<span className="font-medium text-slate-500">No imprime</span>}</td><td className="px-5 text-right"><Button size="sm" variant="outline" onClick={()=>onEditar(x)}><Edit3/>Editar</Button></td></tr>)}</tbody></table></div></CardContent></Card>)}</div>
}

function CaracteristicaModal({item,busy,onClose,onSave}:{item:CaracteristicaFt;busy:boolean;onClose:()=>void;onSave:(r:GuardarCaracteristicaFt)=>void}){
 const [f,setF]=useState<GuardarCaracteristicaFt>({tipoCriterioId:item.tipoCriterioId,valorCuantitativoInicial:item.valorCuantitativoInicial,valorCuantitativoFinal:item.valorCuantitativoFinal,valorCuantitativoIgual:item.valorCuantitativoIgual,valorCualitativo:item.valorCualitativo,unidadDeMedida:item.unidadDeMedida,imprimeCertificado:item.imprimeCertificado,obligatorioCertificado:item.obligatorioCertificado,ordenCertificado:item.ordenCertificado,usuario});
 const setPrint=(v:boolean)=>setF({...f,imprimeCertificado:v,obligatorioCertificado:v?f.obligatorioCertificado:false,ordenCertificado:v?(f.ordenCertificado??item.ordenTecnico??1):null});
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4"><Card className="w-full max-w-2xl bg-white"><CardContent className="space-y-5 p-5"><div className="flex justify-between"><div><p className="text-xs uppercase text-[var(--text-secondary)]">{item.tipoCaracteristicaDescripcion}</p><h3 className="text-lg font-semibold">{item.caracteristicaDescripcion}</h3><p className="text-xs text-[var(--text-secondary)]">Origen ET #{item.versCaractOrigenId??"—"} · Orden técnico {item.ordenTecnico??"—"}</p></div><Button variant="ghost" size="icon" onClick={onClose}><X/></Button></div>
  <div className="grid gap-4 md:grid-cols-2"><Field label="Tipo de criterio"><Input value={item.tipoCriterioDescripcion??String(item.tipoCriterioId)} disabled/></Field><Field label="Unidad"><Input value={f.unidadDeMedida??""} onChange={e=>setF({...f,unidadDeMedida:e.target.value})}/></Field>
   {(item.tipoCriterioId===1||item.tipoCriterioId===9)&&<Field label="Valor"><Input type="number" step="any" value={f.valorCuantitativoInicial??""} onChange={e=>setF({...f,valorCuantitativoInicial:n(e.target.value)})}/></Field>}
   {(item.tipoCriterioId===2||item.tipoCriterioId===10)&&<Field label="Valor"><Input type="number" step="any" value={f.valorCuantitativoFinal??""} onChange={e=>setF({...f,valorCuantitativoFinal:n(e.target.value)})}/></Field>}
   {item.tipoCriterioId===3&&<><Field label="Valor mínimo"><Input type="number" step="any" value={f.valorCuantitativoInicial??""} onChange={e=>setF({...f,valorCuantitativoInicial:n(e.target.value)})}/></Field><Field label="Valor máximo"><Input type="number" step="any" value={f.valorCuantitativoFinal??""} onChange={e=>setF({...f,valorCuantitativoFinal:n(e.target.value)})}/></Field></>}
   {item.tipoCriterioId===11&&<Field label="Valor igual"><Input type="number" step="any" value={f.valorCuantitativoIgual??""} onChange={e=>setF({...f,valorCuantitativoIgual:n(e.target.value)})}/></Field>}
   {(item.tipoCriterioId===4||item.tipoCriterioId===5)&&<Field label="Valor cualitativo"><Input value={f.valorCualitativo??(item.tipoCriterioId===4?"Ausencia":"")} onChange={e=>setF({...f,valorCualitativo:e.target.value})}/></Field>}
  </div>
  <div className="rounded-xl border bg-slate-50 p-4"><h4 className="font-medium">Configuración de certificado</h4><div className="mt-3 grid gap-3 md:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.imprimeCertificado} onChange={e=>setPrint(e.target.checked)}/>Imprime certificado</label><label className={"flex items-center gap-2 text-sm "+(!f.imprimeCertificado?"opacity-40":"")}><input type="checkbox" disabled={!f.imprimeCertificado} checked={f.obligatorioCertificado} onChange={e=>setF({...f,obligatorioCertificado:e.target.checked})}/>Obligatorio</label><Field label="Orden certificado"><Input type="number" min={1} disabled={!f.imprimeCertificado} value={f.ordenCertificado??""} onChange={e=>setF({...f,ordenCertificado:n(e.target.value)})}/></Field></div></div>
  <div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={busy|| (f.imprimeCertificado&&!f.ordenCertificado)} onClick={()=>onSave(f)}><Save/>{busy?"Guardando...":"Guardar cambios"}</Button></div>
 </CardContent></Card></div>
}

function NuevaSeccionModal({busy,onClose,onSave}:{busy:boolean;onClose:()=>void;onSave:(t:string,tipo:"TEXTO"|"LISTA"|"TABLA")=>void}){const [titulo,setTitulo]=useState(""),[tipo,setTipo]=useState<"TEXTO"|"LISTA"|"TABLA">("TEXTO");return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4"><Card className="w-full max-w-lg bg-white"><CardContent className="space-y-4 p-5"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">Agregar sección</h3><p className="text-sm text-[var(--text-secondary)]">Sección personalizada de esta versión de FT.</p></div><Button variant="ghost" size="icon" onClick={onClose}><X/></Button></div><Field label="Título"><Input value={titulo} onChange={e=>setTitulo(e.target.value)}/></Field><Field label="Tipo"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={tipo} onChange={e=>setTipo(e.target.value as typeof tipo)}><option>TEXTO</option><option>LISTA</option><option>TABLA</option></select></Field><div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={busy||!titulo.trim()} onClick={()=>onSave(titulo,tipo)}><Plus/>Agregar</Button></div></CardContent></Card></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5"><span className="text-xs font-medium text-[var(--text-secondary)]">{label}</span>{children}</label>}
function n(v:string){return v===""?null:Number(v)} function cap(v:string){return v.toLowerCase().replace(/(^|\s)\S/g,x=>x.toUpperCase())}
