import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Eye,FilePlus2,Pencil,Search} from "lucide-react";
import {useNavigate} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {crearEt,listarEt,obtenerCatalogosEt} from "./api";

export default function EspecificacionesTecnicasPage(){
 const nav=useNavigate(),qc=useQueryClient(),[buscar,setBuscar]=useState(""),[estado,setEstado]=useState(""),[nueva,setNueva]=useState(false);
 const [form,setForm]=useState({documentoCodigo:"",documentoDescripcionDocumento:"",productoCodigo:"",versionNumero:"1",versionInicioVigencia:"",versionNroPaginas:""});
 const q=useQuery({queryKey:["et-listado"],queryFn:()=>listarEt()});
 const cat=useQuery({queryKey:["et-catalogos"],queryFn:obtenerCatalogosEt});
 const items=useMemo(()=>{const b=buscar.trim().toLowerCase();return(q.data??[]).filter(x=>(!b||[x.documentoCodigo,x.documentoDescripcionDocumento,x.productoCodigo,x.productoDescripcion??""].some(v=>v.toLowerCase().includes(b)))&&(!estado||x.estadoVersion===estado))},[q.data,buscar,estado]);
 const estados=useMemo(()=>Array.from(new Set((q.data??[]).map(x=>x.estadoVersion))),[q.data]);
 const crear=useMutation({mutationFn:crearEt,onSuccess:async r=>{await qc.invalidateQueries({queryKey:["et-listado"]});if(r.versionId)nav(`/documentos/especificaciones/${r.versionId}/editar`)}});
 const submit=(e:React.FormEvent)=>{e.preventDefault();crear.mutate({documentoCodigo:form.documentoCodigo.trim(),documentoDescripcionDocumento:form.documentoDescripcionDocumento.trim(),productoCodigo:form.productoCodigo,versionNumero:Number(form.versionNumero)||1,versionInicioVigencia:form.versionInicioVigencia||null,versionReemplazaAId:null,versionNroPaginas:form.versionNroPaginas?Number(form.versionNroPaginas):null,usuario:"USUARIO_WEB"})};
 return <PageContainer className="space-y-4">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--text-secondary)]">Gestión documental</p><h1 className="mt-1 text-2xl font-semibold">Especificaciones técnicas</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Administra documentos, versiones y especificaciones de producto.</p></div><Button onClick={()=>setNueva(true)}><FilePlus2/>Nueva ET</Button></div>
  {nueva&&<Card><CardContent className="p-5"><div className="mb-4"><h2 className="text-lg font-semibold">Nueva especificación técnica</h2><p className="text-sm text-[var(--text-secondary)]">Crea la cabecera del documento. La ET quedará en BORRADOR para continuar completando sus secciones.</p></div><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Campo label="Código ET"><Input required value={form.documentoCodigo} onChange={e=>setForm({...form,documentoCodigo:e.target.value})} placeholder="Ej. OVOPE-CA-E-253"/></Campo><Campo label="Producto"><select required className="h-9 w-full rounded-lg border bg-white px-3 text-sm" value={form.productoCodigo} onChange={e=>setForm({...form,productoCodigo:e.target.value})}><option value="">Seleccionar producto...</option>{(cat.data?.productos??[]).map(p=><option key={p.productoCodigo} value={p.productoCodigo}>{p.productoCodigo} · {p.productoDescripcion}</option>)}</select></Campo><div className="md:col-span-2"><Campo label="Nombre / descripción del documento"><Input required value={form.documentoDescripcionDocumento} onChange={e=>setForm({...form,documentoDescripcionDocumento:e.target.value})} placeholder="Ej. CLARA LÍQUIDA PASTEURIZADA CL01"/></Campo></div><Campo label="Versión"><Input required min="0.0001" step="0.0001" type="number" value={form.versionNumero} onChange={e=>setForm({...form,versionNumero:e.target.value})}/></Campo><Campo label="Inicio de vigencia"><Input type="date" value={form.versionInicioVigencia} onChange={e=>setForm({...form,versionInicioVigencia:e.target.value})}/></Campo><Campo label="N.º páginas"><Input min="1" type="number" value={form.versionNroPaginas} onChange={e=>setForm({...form,versionNroPaginas:e.target.value})}/></Campo></div>{crear.isError&&<p className="text-sm text-red-600">{crear.error instanceof Error?crear.error.message:"No se pudo crear la ET."}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setNueva(false)} disabled={crear.isPending}>Cancelar</Button><Button type="submit" disabled={crear.isPending||cat.isLoading}>{crear.isPending?"Creando...":"Crear ET"}</Button></div></form></CardContent></Card>}
  <Card><CardContent className="p-4"><div className="grid gap-3 md:grid-cols-[1fr_240px]"><div className="relative"><Search className="absolute left-2.5 top-2 size-4 text-[var(--text-secondary)]"/><Input className="pl-8" placeholder="Buscar por código, producto o descripción..." value={buscar} onChange={e=>setBuscar(e.target.value)}/></div><select className="h-8 rounded-lg border bg-white px-2 text-sm" value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos los estados</option>{estados.map(x=><option key={x}>{x}</option>)}</select></div></CardContent></Card>
  <Card><CardContent className="p-0">{q.isLoading?<div className="p-10 text-center">Cargando especificaciones...</div>:q.isError?<div className="p-10 text-center text-red-600">No se pudo cargar el listado.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Código</th><th>Producto</th><th>Versión</th><th>Inicio vigencia</th><th>Estado</th><th>Actualizado</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>{items.map(x=><tr key={x.versionId} className="border-t hover:bg-slate-50/70"><td className="px-5 py-3"><b>{x.documentoCodigo}</b><div className="max-w-[320px] truncate text-xs text-[var(--text-secondary)]">{x.documentoDescripcionDocumento}</div></td><td><b>{x.productoCodigo}</b><div className="text-xs text-[var(--text-secondary)]">{x.productoDescripcion??"—"}</div></td><td>{x.versionNumero??"—"}</td><td>{fecha(x.versionInicioVigencia)}</td><td><Badge variant="outline">{x.estadoVersion}</Badge></td><td>{fecha(x.audFechaActualizacion??x.audFechaCreacion)}</td><td className="px-5 text-right"><div className="inline-flex gap-1"><Button variant="outline" size="sm" onClick={()=>nav(`/documentos/especificaciones/${x.versionId}`)}><Eye/>Ver detalle</Button>{x.permiteEditar&&<Button size="sm" onClick={()=>nav(`/documentos/especificaciones/${x.versionId}/editar`)}><Pencil/>Editar</Button>}</div></td></tr>)}{!items.length&&<tr><td colSpan={7} className="p-10 text-center text-[var(--text-secondary)]">No se encontraron especificaciones técnicas.</td></tr>}</tbody></table></div>}</CardContent></Card>
  <p className="text-xs text-[var(--text-secondary)]">{items.length} especificación(es) mostrada(s).</p>
 </PageContainer>
}
function fecha(v:string|null){return v?new Date(v).toLocaleDateString("es-PE"):"—"}

function Campo({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label>}
