import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowDown,ArrowLeft,ArrowUp,Edit3,GripVertical,Plus,Save,Trash2,X} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {agregarSeccionVersionEt,eliminarCaracteristica,guardarCaracteristica,guardarContenidoSeccionEt,obtenerCatalogosEt,obtenerContenidoSeccionesEt,obtenerEt,obtenerSeccionesEt,quitarSeccionVersionEt,reordenarSeccionesVersionEt} from "./api";
import type {CaracteristicaEt,GuardarCaracteristicaEt} from "./types";

const vacio:GuardarCaracteristicaEt={versCaractId:null,caracteristicaId:0,tipoCriterioId:0,valorCuantitativoInicial:null,valorCuantitativoFinal:null,valorCuantitativoIgual:null,valorCualitativo:null,faseId:null,esObligatorio:true,orden:1,usuario:"USUARIO_WEB"};
const num=(v:string)=>v===""?null:Number(v);
export default function EspecificacionTecnicaPage(){
 const nav=useNavigate(),qc=useQueryClient(),{versionId}=useParams(),id=Number(versionId);
 const [form,setForm]=useState<GuardarCaracteristicaEt|null>(null); const [error,setError]=useState(""); const [seccionActiva,setSeccionActiva]=useState<number|null>(null); const [modalAgregar,setModalAgregar]=useState(false); const [contenido,setContenido]=useState(""); const [tipoFiltro,setTipoFiltro]=useState<number>(0); const [busquedaCaracteristica,setBusquedaCaracteristica]=useState(""); const [selectorAbierto,setSelectorAbierto]=useState(false);
 const et=useQuery({queryKey:["et",id],queryFn:()=>obtenerEt(id),enabled:id>0});
 const cat=useQuery({queryKey:["et-catalogos"],queryFn:obtenerCatalogosEt});
 const secCat=useQuery({queryKey:["et-secciones"],queryFn:obtenerSeccionesEt});
 const contenidos=useQuery({queryKey:["et-contenidos",id],queryFn:()=>obtenerContenidoSeccionesEt(id),enabled:id>0});
 const save=useMutation({mutationFn:(x:GuardarCaracteristicaEt)=>guardarCaracteristica(id,x),onSuccess:async()=>{setForm(null);setError("");await qc.invalidateQueries({queryKey:["et",id]})},onError:(e:Error)=>setError(e.message)});
 const del=useMutation({mutationFn:(vc:number)=>eliminarCaracteristica(id,vc),onSuccess:()=>qc.invalidateQueries({queryKey:["et",id]}),onError:(e:Error)=>setError(e.message)});
 const refrescar=async()=>{await Promise.all([qc.invalidateQueries({queryKey:["et",id]}),qc.invalidateQueries({queryKey:["et-contenidos",id]})])};
 const addSec=useMutation({mutationFn:(seccionId:number)=>agregarSeccionVersionEt(id,{seccionId,orden:null,usuario:"USUARIO_WEB"}),onSuccess:async()=>{setModalAgregar(false);await refrescar()},onError:(e:Error)=>setError(e.message)});
 const removeSec=useMutation({mutationFn:(versSeccId:number)=>quitarSeccionVersionEt(id,versSeccId),onSuccess:async()=>{setSeccionActiva(null);await refrescar()},onError:(e:Error)=>setError(e.message)});
 const saveContenido=useMutation({mutationFn:()=>guardarContenidoSeccionEt(id,seccionActiva!,contenido),onSuccess:()=>refrescar(),onError:(e:Error)=>setError(e.message)});
 const moverSeccion=(idx:number,dir:-1|1)=>{const s=[...(et.data?.secciones??[])].sort((a,b)=>(a.orden??0)-(b.orden??0));const j=idx+dir;if(j<1||j>=s.length)return;[s[idx],s[j]]=[s[j],s[idx]];reordenarSeccionesVersionEt(id,{secciones:s.map((x,i)=>({versSeccId:x.versSeccId,orden:i+1})),usuario:"USUARIO_WEB"}).then(refrescar).catch(e=>setError(e.message))};
 useEffect(()=>{if(et.data?.secciones.length&&!seccionActiva)setSeccionActiva([...et.data.secciones].sort((a,b)=>(a.orden??0)-(b.orden??0))[0].versSeccId)},[et.data?.secciones,seccionActiva]);
 useEffect(()=>{const x=contenidos.data?.find(x=>x.versSeccId===seccionActiva);setContenido(x?.contenido??"")},[contenidos.data,seccionActiva]);
 const selected=useMemo(()=>cat.data?.caracteristicas.find(x=>x.caracteristicaId===form?.caracteristicaId),[cat.data,form?.caracteristicaId]);
 const caracteristicasFiltradas=useMemo(()=>{const b=busquedaCaracteristica.trim().toLowerCase();return (cat.data?.caracteristicas??[]).filter(x=>(!tipoFiltro||x.tipoCaractId===tipoFiltro)&&(!b||x.caracteristicaDescripcion.toLowerCase().includes(b)))},[cat.data,tipoFiltro,busquedaCaracteristica]);
 if(et.isLoading||cat.isLoading||secCat.isLoading||contenidos.isLoading)return <PageContainer><div className="py-16 text-center">Cargando Especificación Técnica...</div></PageContainer>;
 if(et.isError||!et.data||!cat.data)return <PageContainer><div className="py-16 text-center text-red-600">No se pudo cargar la Especificación Técnica.</div></PageContainer>;
 const info=et.data.informacionGeneral,editable=info.permiteEditar;
 const editar=(x:CaracteristicaEt)=>setForm({versCaractId:x.versCaractId,caracteristicaId:x.caracteristicaId,tipoCriterioId:x.tipoCriterioId??0,valorCuantitativoInicial:x.valorCuantitativoInicial,valorCuantitativoFinal:x.valorCuantitativoFinal,valorCuantitativoIgual:x.valorCuantitativoIgual,valorCualitativo:x.valorCualitativo,faseId:x.faseId,esObligatorio:x.esObligatorio,orden:x.orden??1,usuario:"USUARIO_WEB"});
 const estructura=[...et.data.secciones].sort((a,b)=>(a.orden??0)-(b.orden??0));
 const activa=estructura.find(x=>x.versSeccId===seccionActiva)??estructura[0];
 const disponibles=(secCat.data?.secciones??[]).filter(x=>!estructura.some(y=>y.seccionId===x.seccionId));
 const criterio=cat.data.tiposCriterio.find(x=>x.tipoCriterioId===form?.tipoCriterioId)?.tipoCriterio;
 return <PageContainer className="space-y-4">
  <div className="flex items-start justify-between gap-4"><div><Button variant="ghost" size="sm" className="-ml-2 mb-1" onClick={()=>nav("/documentos/especificaciones")}><ArrowLeft/>Especificaciones</Button><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{info.documentoCodigo}</h1><Badge variant="outline">{info.estadoVersion}</Badge></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{info.documentoDescripcionDocumento} · {info.productoCodigo} {info.productoDescripcion}</p></div><div className="text-right text-xs text-[var(--text-secondary)]">Versión<div className="text-lg font-semibold text-[var(--text)]">{info.versionNumero??"—"}</div></div></div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <Card><CardContent className="p-5"><div className="grid gap-4 md:grid-cols-4"><Info l="Estado" v={info.estadoVersion}/><Info l="Producto" v={info.productoCodigo}/><Info l="Inicio vigencia" v={info.versionInicioVigencia?.slice(0,10)??"—"}/><Info l="Páginas" v={String(info.versionNroPaginas??"—")}/></div>{info.versionDescripcion&&<p className="mt-4 border-t pt-4 text-sm text-[var(--text-secondary)]">{info.versionDescripcion}</p>}</CardContent></Card>
  <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
   <Card><CardContent className="p-0"><div className="border-b px-4 py-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Estructura</h2><p className="text-xs text-[var(--text-secondary)]">{estructura.length} secciones</p></div><Button size="sm" variant="outline" disabled={!editable} onClick={()=>setModalAgregar(true)}><Plus/>Agregar</Button></div></div><div className="p-2">{estructura.map((s,i)=><div key={s.versSeccId} className={`mb-1 flex items-center gap-1 rounded-lg border ${activa?.versSeccId===s.versSeccId?"border-slate-400 bg-slate-50":"border-transparent"}`}><button className="flex min-w-0 flex-1 items-center gap-2 px-2 py-3 text-left" onClick={()=>setSeccionActiva(s.versSeccId)}><GripVertical className="size-4 shrink-0 text-slate-400"/><span className="w-6 text-xs font-semibold text-slate-400">{String(i+1).padStart(2,"0")}</span><span className="truncate text-sm font-medium">{s.seccionDescripcion}</span></button>{editable&&s.permiteReordenar&&<div className="mr-1 flex"><Button variant="ghost" size="icon-sm" disabled={i<=1} onClick={()=>moverSeccion(i,-1)}><ArrowUp/></Button><Button variant="ghost" size="icon-sm" disabled={i===estructura.length-1} onClick={()=>moverSeccion(i,1)}><ArrowDown/></Button></div>}{editable&&s.puedeEliminarse&&<Button className="mr-1" variant="ghost" size="icon-sm" onClick={()=>confirm(`¿Retirar ${s.seccionDescripcion} de esta ET?`)&&removeSec.mutate(s.versSeccId)}><X/></Button>}</div>)}</div></CardContent></Card>
   <div className="min-w-0">{activa?.seccionId===18?<>  <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Características</h2><p className="text-xs text-[var(--text-secondary)]">{et.data.caracteristicas.length} configuradas en esta versión.</p></div><Button disabled={!editable} onClick={()=>{setError("");setTipoFiltro(0);setBusquedaCaracteristica("");setSelectorAbierto(false);setForm({...vacio,orden:et.data.caracteristicas.length+1})}}><Plus/>Agregar característica</Button></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Característica</th><th>Criterio</th><th>Especificación</th><th>Fase</th><th>Obligatoria</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>{et.data.caracteristicas.map(x=><tr key={x.versCaractId} className="border-t"><td className="px-5 py-3"><b>{x.caracteristica}</b><div className="text-xs text-[var(--text-secondary)]">{x.tipoCaracteristica} · {x.metodoEnsayo??"Sin método"}</div></td><td>{x.tipoCriterio}</td><td>{spec(x)}</td><td>{x.faseCodigo??"—"}</td><td>{x.esObligatorio?"Sí":"No"}</td><td className="px-5 text-right"><div className="inline-flex gap-1"><Button size="icon-sm" variant="outline" disabled={!editable} onClick={()=>editar(x)}><Edit3/></Button><Button size="icon-sm" variant="destructive" disabled={!editable||del.isPending} onClick={()=>{if(confirm(`¿Eliminar ${x.caracteristica} de esta ET?`))del.mutate(x.versCaractId)}}><Trash2/></Button></div></td></tr>)}</tbody></table></div>
  </CardContent></Card>
</>:activa&&!activa.esBase?<Card><CardContent className="p-0"><div className="border-b px-5 py-4"><h2 className="font-semibold">{activa.seccionDescripcion}</h2><p className="text-xs text-[var(--text-secondary)]">Contenido personalizado de esta versión.</p></div><div className="space-y-4 p-5"><textarea className="min-h-64 w-full resize-y rounded-lg border bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-slate-200" value={contenido} disabled={!editable} onChange={e=>setContenido(e.target.value)} placeholder="Ingrese el contenido de la sección..."/><div className="flex justify-end"><Button disabled={!editable||saveContenido.isPending} onClick={()=>saveContenido.mutate()}><Save/>{saveContenido.isPending?"Guardando...":"Guardar contenido"}</Button></div></div></CardContent></Card>:<Card><CardContent className="p-6"><h2 className="font-semibold">{activa?.seccionDescripcion??"Sección"}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Esta sección utiliza almacenamiento especializado. Su formulario de edición se incorporará sobre este panel sin alterar la estructura de la ET.</p></CardContent></Card>}</div>
  </div>
  {modalAgregar&&<div className="fixed inset-0 z-40 flex items-center justify-center bg-black/30 p-4"><Card className="w-full max-w-lg bg-white"><CardContent className="p-5"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold">Agregar sección</h3><p className="text-sm text-[var(--text-secondary)]">Selecciona una sección disponible para esta ET.</p></div><Button variant="ghost" size="icon" onClick={()=>setModalAgregar(false)}><X/></Button></div><div className="mt-4 max-h-80 space-y-2 overflow-auto">{disponibles.length?disponibles.map(s=><button key={s.seccionId} className="w-full rounded-lg border p-3 text-left hover:bg-slate-50" disabled={addSec.isPending} onClick={()=>addSec.mutate(s.seccionId)}><span className="block text-sm font-medium">{s.seccionDescripcion}</span><span className="text-xs text-[var(--text-secondary)]">{s.esBase?"Sección base":"Personalizada"} · {s.tipoSeccion??"Contenido"}</span></button>):<div className="py-8 text-center text-sm text-[var(--text-secondary)]">No hay más secciones disponibles.</div>}</div></CardContent></Card></div>}
  {form&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><Card className="w-full max-w-2xl bg-white"><CardContent className="space-y-4 p-5"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">{form.versCaractId?"Editar":"Agregar"} característica</h3><p className="text-xs text-[var(--text-secondary)]">La unidad y método provienen del maestro de características.</p></div><Button variant="ghost" size="icon" onClick={()=>setForm(null)}><X/></Button></div>
   <div className="grid gap-4 md:grid-cols-2"><Field label="Tipo de característica"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={tipoFiltro} onChange={e=>{setTipoFiltro(Number(e.target.value));setBusquedaCaracteristica("");setSelectorAbierto(false);setForm({...form,caracteristicaId:0})}}><option value={0}>Seleccione...</option>{cat.data.tiposCaracteristica.map((x:any)=><option key={x.tipoCaractId} value={x.tipoCaractId}>{x.tipoCaractDescripcion}</option>)}</select></Field><Field label="Característica"><div className="relative"><Input disabled={!tipoFiltro} value={selected?selected.caracteristicaDescripcion:busquedaCaracteristica} placeholder={tipoFiltro?"Escriba o seleccione...":"Seleccione primero el tipo"} onFocus={()=>tipoFiltro&&setSelectorAbierto(true)} onChange={e=>{setForm({...form,caracteristicaId:0});setBusquedaCaracteristica(e.target.value);setSelectorAbierto(true)}}/>{selectorAbierto&&tipoFiltro>0&&<div className="absolute z-20 mt-1 max-h-52 w-full overflow-auto rounded-lg border bg-white p-1 shadow-lg">{caracteristicasFiltradas.length?caracteristicasFiltradas.map(x=><button key={x.caracteristicaId} type="button" className="block w-full rounded-md px-3 py-2 text-left text-sm hover:bg-slate-50" onMouseDown={e=>e.preventDefault()} onClick={()=>{setForm({...form,caracteristicaId:x.caracteristicaId});setBusquedaCaracteristica("");setSelectorAbierto(false)}}><b>{x.caracteristicaDescripcion}</b><span className="ml-2 text-xs text-[var(--text-secondary)]">{x.unidad??"Sin unidad"} · {x.metodoEnsayo??"Sin método"}</span></button>):<div className="px-3 py-3 text-sm text-[var(--text-secondary)]">No hay características que coincidan.</div>}</div>}</div></Field><Field label="Unidad / Método"><div className="rounded-lg bg-slate-50 px-3 py-2 text-sm">{selected?`${selected.unidad??"—"} · ${selected.metodoEnsayo??"Sin método"}`:"Seleccione una característica"}</div></Field>
   <Field label="Criterio"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={form.tipoCriterioId} onChange={e=>setForm({...form,tipoCriterioId:Number(e.target.value),valorCuantitativoInicial:null,valorCuantitativoFinal:null,valorCuantitativoIgual:null,valorCualitativo:null})}><option value={0}>Seleccione...</option>{cat.data.tiposCriterio.map(x=><option key={x.tipoCriterioId} value={x.tipoCriterioId}>{x.tipoCriterio}</option>)}</select></Field><Field label="Fase"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={form.faseId??""} onChange={e=>setForm({...form,faseId:e.target.value?Number(e.target.value):null})}><option value="">Sin fase</option>{cat.data.fases.map(x=><option key={x.faseId} value={x.faseId}>{x.faseCodigo} · {x.faseDescripcion}</option>)}</select></Field>
   {criterio==="MINIMO"&&<Field label="Valor mínimo"><Input type="number" step="any" value={form.valorCuantitativoInicial??""} onChange={e=>setForm({...form,valorCuantitativoInicial:num(e.target.value)})}/></Field>}
   {criterio==="MAXIMO"&&<Field label="Valor máximo"><Input type="number" step="any" value={form.valorCuantitativoFinal??""} onChange={e=>setForm({...form,valorCuantitativoFinal:num(e.target.value)})}/></Field>}
   {criterio==="RANGO"&&<><Field label="Valor mínimo"><Input type="number" step="any" value={form.valorCuantitativoInicial??""} onChange={e=>setForm({...form,valorCuantitativoInicial:num(e.target.value)})}/></Field><Field label="Valor máximo"><Input type="number" step="any" value={form.valorCuantitativoFinal??""} onChange={e=>setForm({...form,valorCuantitativoFinal:num(e.target.value)})}/></Field></>}
   {criterio==="CUALITATIVO"&&<Field label="Especificación cualitativa"><Input value={form.valorCualitativo??""} onChange={e=>setForm({...form,valorCualitativo:e.target.value})}/></Field>}
   {criterio==="AUSENCIA"&&<Field label="Especificación"><Input value="Ausencia" disabled/></Field>}
   <Field label="Orden"><Input type="number" min={1} value={form.orden} onChange={e=>setForm({...form,orden:Number(e.target.value)})}/></Field><Field label="Obligatoria"><label className="flex h-8 items-center gap-2"><input type="checkbox" checked={form.esObligatorio} onChange={e=>setForm({...form,esObligatorio:e.target.checked})}/>Sí, requerida para evaluación</label></Field></div>
   <div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={()=>setForm(null)}>Cancelar</Button><Button disabled={save.isPending||!form.caracteristicaId||!form.tipoCriterioId} onClick={()=>save.mutate(form)}><Save/>{save.isPending?"Guardando...":"Guardar"}</Button></div>
  </CardContent></Card></div>}
 </PageContainer>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5"><span className="text-xs font-medium text-[var(--text-secondary)]">{label}</span>{children}</label>}
function Info({l,v}:{l:string;v:string}){return <div><p className="text-xs text-[var(--text-secondary)]">{l}</p><p className="mt-1 font-medium">{v}</p></div>}
function spec(x:CaracteristicaEt){switch(x.tipoCriterio){case"MINIMO":return `≥ ${x.valorCuantitativoInicial} ${x.unidad??""}`;case"MAXIMO":return `≤ ${x.valorCuantitativoFinal} ${x.unidad??""}`;case"RANGO":return `${x.valorCuantitativoInicial} – ${x.valorCuantitativoFinal} ${x.unidad??""}`;case"AUSENCIA":return x.valorCualitativo??"Ausencia";default:return x.valorCualitativo??"—"}}
