import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowLeft,Edit3,Plus,Save,Trash2,X} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {eliminarCaracteristica,guardarCaracteristica,obtenerCatalogosEt,obtenerEt} from "./api";
import type {CaracteristicaEt,GuardarCaracteristicaEt} from "./types";

const vacio:GuardarCaracteristicaEt={versCaractId:null,caracteristicaId:0,tipoCriterioId:0,valorCuantitativoInicial:null,valorCuantitativoFinal:null,valorCuantitativoIgual:null,valorCualitativo:null,faseId:null,esObligatorio:true,orden:1,usuario:"USUARIO_WEB"};
const num=(v:string)=>v===""?null:Number(v);
export default function EspecificacionTecnicaPage(){
 const nav=useNavigate(),qc=useQueryClient(),{versionId}=useParams(),id=Number(versionId);
 const [form,setForm]=useState<GuardarCaracteristicaEt|null>(null); const [error,setError]=useState("");
 const et=useQuery({queryKey:["et",id],queryFn:()=>obtenerEt(id),enabled:id>0});
 const cat=useQuery({queryKey:["et-catalogos"],queryFn:obtenerCatalogosEt});
 const save=useMutation({mutationFn:(x:GuardarCaracteristicaEt)=>guardarCaracteristica(id,x),onSuccess:async()=>{setForm(null);setError("");await qc.invalidateQueries({queryKey:["et",id]})},onError:(e:Error)=>setError(e.message)});
 const del=useMutation({mutationFn:(vc:number)=>eliminarCaracteristica(id,vc),onSuccess:()=>qc.invalidateQueries({queryKey:["et",id]}),onError:(e:Error)=>setError(e.message)});
 const selected=useMemo(()=>cat.data?.caracteristicas.find(x=>x.caracteristicaId===form?.caracteristicaId),[cat.data,form?.caracteristicaId]);
 if(et.isLoading||cat.isLoading)return <PageContainer><div className="py-16 text-center">Cargando Especificación Técnica...</div></PageContainer>;
 if(et.isError||!et.data||!cat.data)return <PageContainer><div className="py-16 text-center text-red-600">No se pudo cargar la Especificación Técnica.</div></PageContainer>;
 const info=et.data.informacionGeneral,editable=info.permiteEditar;
 const editar=(x:CaracteristicaEt)=>setForm({versCaractId:x.versCaractId,caracteristicaId:x.caracteristicaId,tipoCriterioId:x.tipoCriterioId??0,valorCuantitativoInicial:x.valorCuantitativoInicial,valorCuantitativoFinal:x.valorCuantitativoFinal,valorCuantitativoIgual:x.valorCuantitativoIgual,valorCualitativo:x.valorCualitativo,faseId:x.faseId,esObligatorio:x.esObligatorio,orden:x.orden??1,usuario:"USUARIO_WEB"});
 const criterio=cat.data.tiposCriterio.find(x=>x.tipoCriterioId===form?.tipoCriterioId)?.tipoCriterio;
 return <PageContainer className="space-y-4">
  <div className="flex items-start justify-between gap-4"><div><Button variant="ghost" size="sm" className="-ml-2 mb-1" onClick={()=>nav("/documentos/especificaciones")}><ArrowLeft/>Especificaciones</Button><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{info.documentoCodigo}</h1><Badge variant="outline">{info.estadoVersion}</Badge></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{info.documentoDescripcionDocumento} · {info.productoCodigo} {info.productoDescripcion}</p></div><div className="text-right text-xs text-[var(--text-secondary)]">Versión<div className="text-lg font-semibold text-[var(--text)]">{info.versionNumero??"—"}</div></div></div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <Card><CardContent className="p-5"><div className="grid gap-4 md:grid-cols-4"><Info l="Estado" v={info.estadoVersion}/><Info l="Producto" v={info.productoCodigo}/><Info l="Inicio vigencia" v={info.versionInicioVigencia?.slice(0,10)??"—"}/><Info l="Páginas" v={String(info.versionNroPaginas??"—")}/></div>{info.versionDescripcion&&<p className="mt-4 border-t pt-4 text-sm text-[var(--text-secondary)]">{info.versionDescripcion}</p>}</CardContent></Card>
  <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Características</h2><p className="text-xs text-[var(--text-secondary)]">{et.data.caracteristicas.length} configuradas en esta versión.</p></div><Button disabled={!editable} onClick={()=>{setError("");setForm({...vacio,orden:et.data.caracteristicas.length+1})}}><Plus/>Agregar característica</Button></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Característica</th><th>Criterio</th><th>Especificación</th><th>Fase</th><th>Obligatoria</th><th className="px-5 text-right">Acciones</th></tr></thead><tbody>{et.data.caracteristicas.map(x=><tr key={x.versCaractId} className="border-t"><td className="px-5 py-3"><b>{x.caracteristica}</b><div className="text-xs text-[var(--text-secondary)]">{x.tipoCaracteristica} · {x.metodoEnsayo??"Sin método"}</div></td><td>{x.tipoCriterio}</td><td>{spec(x)}</td><td>{x.faseCodigo??"—"}</td><td>{x.esObligatorio?"Sí":"No"}</td><td className="px-5 text-right"><div className="inline-flex gap-1"><Button size="icon-sm" variant="outline" disabled={!editable} onClick={()=>editar(x)}><Edit3/></Button><Button size="icon-sm" variant="destructive" disabled={!editable||del.isPending} onClick={()=>{if(confirm(`¿Eliminar ${x.caracteristica} de esta ET?`))del.mutate(x.versCaractId)}}><Trash2/></Button></div></td></tr>)}</tbody></table></div>
  </CardContent></Card>
  {form&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><Card className="w-full max-w-2xl bg-white"><CardContent className="space-y-4 p-5"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">{form.versCaractId?"Editar":"Agregar"} característica</h3><p className="text-xs text-[var(--text-secondary)]">La unidad y método provienen del maestro de características.</p></div><Button variant="ghost" size="icon" onClick={()=>setForm(null)}><X/></Button></div>
   <div className="grid gap-4 md:grid-cols-2"><Field label="Característica"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={form.caracteristicaId} onChange={e=>setForm({...form,caracteristicaId:Number(e.target.value)})}><option value={0}>Seleccione...</option>{cat.data.caracteristicas.map(x=><option key={x.caracteristicaId} value={x.caracteristicaId}>{x.caracteristicaDescripcion}</option>)}</select></Field><Field label="Tipo / Unidad / Método"><div className="rounded-lg bg-slate-50 px-3 py-2 text-sm">{selected? `${selected.tipoCaracteristica} · ${selected.unidad??"—"} · ${selected.metodoEnsayo??"Sin método"}`:"Seleccione una característica"}</div></Field>
   <Field label="Criterio"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={form.tipoCriterioId} onChange={e=>setForm({...form,tipoCriterioId:Number(e.target.value),valorCuantitativoInicial:null,valorCuantitativoFinal:null,valorCuantitativoIgual:null,valorCualitativo:null})}><option value={0}>Seleccione...</option>{cat.data.tiposCriterio.map(x=><option key={x.tipoCriterioId} value={x.tipoCriterioId}>{x.tipoCriterio}</option>)}</select></Field><Field label="Fase"><select className="h-8 w-full rounded-lg border px-2 text-sm" value={form.faseId??""} onChange={e=>setForm({...form,faseId:e.target.value?Number(e.target.value):null})}><option value="">Sin fase</option>{cat.data.fases.map(x=><option key={x.faseId} value={x.faseId}>{x.faseCodigo} · {x.faseDescripcion}</option>)}</select></Field>
   {criterio==="MINIMO"&&<Field label="Valor mínimo"><Input type="number" step="any" value={form.valorCuantitativoInicial??""} onChange={e=>setForm({...form,valorCuantitativoInicial:num(e.target.value)})}/></Field>}
   {criterio==="MAXIMO"&&<Field label="Valor máximo"><Input type="number" step="any" value={form.valorCuantitativoFinal??""} onChange={e=>setForm({...form,valorCuantitativoFinal:num(e.target.value)})}/></Field>}
   {criterio==="RANGO"&&<><Field label="Valor mínimo"><Input type="number" step="any" value={form.valorCuantitativoInicial??""} onChange={e=>setForm({...form,valorCuantitativoInicial:num(e.target.value)})}/></Field><Field label="Valor máximo"><Input type="number" step="any" value={form.valorCuantitativoFinal??""} onChange={e=>setForm({...form,valorCuantitativoFinal:num(e.target.value)})}/></Field></>}
   {criterio==="CUALITATIVO"&&<Field label="Especificación cualitativa"><Input value={form.valorCualitativo??""} onChange={e=>setForm({...form,valorCualitativo:e.target.value})}/></Field>}
   {criterio==="AUSENCIA"&&<Field label="Especificación"><Input value="Ausencia" disabled/></Field>}
   <Field label="Orden"><Input type="number" min={1} value={form.orden} onChange={e=>setForm({...form,orden:Number(e.target.value)})}/></Field><Field label="Obligatoria"><label className="flex h-8 items-center gap-2"><input type="checkbox" checked={form.esObligatorio} onChange={e=>setForm({...form,esObligatorio:e.target.checked})}/>Sí, requerida para evaluación</label></Field></div>
   <div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={()=>setForm(null)}>Cancelar</Button><Button disabled={save.isPending||!form.caracteristicaId||!form.tipoCriterioId} onClick={()=>save.mutate(form)}><Save/>{save.isPending?"Guardando...":"Guardar"}</Button></div>
  </CardContent></Card></div>}
 </PageContainer>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5"><span className="text-xs font-medium text-[var(--text-secondary)]">{label}</span>{children}</label>}
function Info({l,v}:{l:string;v:string}){return <div><p className="text-xs text-[var(--text-secondary)]">{l}</p><p className="mt-1 font-medium">{v}</p></div>}
function spec(x:CaracteristicaEt){switch(x.tipoCriterio){case"MINIMO":return `≥ ${x.valorCuantitativoInicial} ${x.unidad??""}`;case"MAXIMO":return `≤ ${x.valorCuantitativoFinal} ${x.unidad??""}`;case"RANGO":return `${x.valorCuantitativoInicial} – ${x.valorCuantitativoFinal} ${x.unidad??""}`;case"AUSENCIA":return x.valorCualitativo??"Ausencia";default:return x.valorCualitativo??"—"}}
