import {useEffect,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowDown,ArrowLeft,ArrowUp,Check,FilePlus2,Plus,X} from "lucide-react";
import {useNavigate} from "react-router-dom";
import PageContainer from "@/components/common/PageContainer";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {crearEt,crearSeccionEt,obtenerCatalogosEt,obtenerSeccionesEt} from "./api";

export default function NuevaEspecificacionTecnicaPage(){
 const nav=useNavigate(),qc=useQueryClient(),[paso,setPaso]=useState(1),[seleccion,setSeleccion]=useState<number[]>([]),[inicializado,setInicializado]=useState(false),[modal,setModal]=useState(false);
 const [form,setForm]=useState({documentoCodigo:"",documentoDescripcionDocumento:"",productoCodigo:"",versionNumero:"1",versionInicioVigencia:"",versionNroPaginas:""});
 const [secForm,setSecForm]=useState({seccionDescripcion:"",idTipoSeccion:"1"});
 const cat=useQuery({queryKey:["et-catalogos"],queryFn:obtenerCatalogosEt});
 const sec=useQuery({queryKey:["et-secciones"],queryFn:obtenerSeccionesEt});
 useEffect(()=>{if(sec.data&&!inicializado){setSeleccion(sec.data.secciones.filter(x=>x.esBase).sort((a,b)=>a.ordenDefault-b.ordenDefault).map(x=>x.seccionId));setInicializado(true)}},[sec.data,inicializado]);
 const crear=useMutation({mutationFn:crearEt,onSuccess:async r=>{await qc.invalidateQueries({queryKey:["et-listado"]});if(r.versionId)nav(`/documentos/especificaciones/${r.versionId}/editar`)}});
 const crearSec=useMutation({mutationFn:crearSeccionEt,onSuccess:async r=>{await qc.invalidateQueries({queryKey:["et-secciones"]});const nuevo=Number(r.seccionId);if(nuevo&&!seleccion.includes(nuevo))setSeleccion(s=>[...s,nuevo]);setSecForm({seccionDescripcion:"",idTipoSeccion:"1"});setModal(false)}});
 const secciones=sec.data?.secciones??[];
 const toggle=(id:number)=>{if(id===11)return;setSeleccion(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])};
 const mover=(idx:number,dir:-1|1)=>setSeleccion(s=>{const n=[...s],j=idx+dir;if(j<1||j>=n.length)return s;[n[idx],n[j]]=[n[j],n[idx]];return n});
 const submit=(e:React.FormEvent)=>{e.preventDefault();crear.mutate({documentoCodigo:form.documentoCodigo.trim(),documentoDescripcionDocumento:form.documentoDescripcionDocumento.trim(),productoCodigo:form.productoCodigo,versionNumero:Number(form.versionNumero)||1,versionInicioVigencia:form.versionInicioVigencia||null,versionReemplazaAId:null,versionNroPaginas:form.versionNroPaginas?Number(form.versionNroPaginas):null,secciones:seleccion.map((seccionId,i)=>({seccionId,orden:i+1})),usuario:"USUARIO_WEB"})};
 return <PageContainer className="space-y-4">
  <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--text-secondary)]">Gestión documental</p><h1 className="mt-1 text-2xl font-semibold">Nueva especificación técnica</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Define primero el producto y la estructura que realmente aplicará al documento.</p></div><div className="flex gap-2"><Badge variant={paso===1?"default":"outline"}>1 Estructura</Badge><Badge variant={paso===2?"default":"outline"}>2 Datos ET</Badge></div></div>
  <Card><CardContent className="p-6">{paso===1?<div className="space-y-6">
   <Campo label="1. Producto"><select className="h-10 w-full rounded-lg border bg-white px-3 text-sm" value={form.productoCodigo} onChange={e=>setForm({...form,productoCodigo:e.target.value})}><option value="">Seleccionar producto...</option>{(cat.data?.productos??[]).map(p=><option key={p.productoCodigo} value={p.productoCodigo}>{p.productoCodigo} · {p.productoDescripcion}</option>)}</select></Campo>
   <div><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="font-semibold">2. Secciones disponibles</h2><p className="text-sm text-[var(--text-secondary)]">Selecciona las secciones que aplican. Información general siempre es obligatoria.</p></div><Button type="button" variant="outline" onClick={()=>setModal(true)}><Plus/>Crear sección</Button></div>
    {sec.isLoading?<div className="rounded-lg border p-8 text-center">Cargando secciones...</div>:sec.isError?<div className="rounded-lg border p-8 text-center text-red-600">No se pudieron cargar las secciones.</div>:<div className="grid gap-2 md:grid-cols-2">{secciones.map(s=>{const on=seleccion.includes(s.seccionId),fija=s.seccionId===11;return <button key={s.seccionId} type="button" disabled={fija} onClick={()=>toggle(s.seccionId)} className={`flex items-center gap-3 rounded-lg border p-3 text-left transition ${on?"border-slate-400 bg-slate-50":"bg-white opacity-70"}`}><span className={`flex size-5 items-center justify-center rounded border ${on?"bg-slate-900 text-white":""}`}>{on&&<Check className="size-3.5"/>}</span><span className="flex-1"><span className="block text-sm font-medium">{s.seccionDescripcion}</span>{!s.esBase&&<span className="text-xs text-[var(--text-secondary)]">Personalizada</span>}</span>{fija&&<Badge variant="outline">Obligatoria</Badge>}</button>})}</div>}
   </div>
   <div className="rounded-lg border bg-slate-50 p-4"><div className="mb-3"><h2 className="font-semibold">Orden de la estructura</h2><p className="text-xs text-[var(--text-secondary)]">{seleccion.length} secciones seleccionadas</p></div><div className="space-y-1">{seleccion.map((id,i)=>{const s=secciones.find(x=>x.seccionId===id);if(!s)return null;const fija=id===11;return <div key={id} className="flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm"><b className="w-6 text-[var(--text-secondary)]">{i+1}.</b><span className="flex-1">{s.seccionDescripcion}</span>{!s.esBase&&<Badge variant="outline">Personalizada</Badge>}{!fija&&<><Button type="button" variant="ghost" size="icon-sm" disabled={i<=1} onClick={()=>mover(i,-1)}><ArrowUp/></Button><Button type="button" variant="ghost" size="icon-sm" disabled={i===seleccion.length-1} onClick={()=>mover(i,1)}><ArrowDown/></Button><Button type="button" variant="ghost" size="icon-sm" onClick={()=>toggle(id)}><X/></Button></>}</div>})}</div></div>
   <div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={()=>nav("/documentos/especificaciones")}>Cancelar</Button><Button disabled={!form.productoCodigo||!seleccion.includes(11)} onClick={()=>setPaso(2)}>Continuar</Button></div>
  </div>:<form onSubmit={submit} className="space-y-5">
   <div className="rounded-lg border bg-slate-50 px-4 py-3 text-sm"><b>{form.productoCodigo}</b> · {cat.data?.productos.find(x=>x.productoCodigo===form.productoCodigo)?.productoDescripcion}<span className="ml-3 text-[var(--text-secondary)]">{seleccion.length} secciones</span></div>
   <div className="grid gap-4 md:grid-cols-2"><Campo label="Código ET"><Input required value={form.documentoCodigo} onChange={e=>setForm({...form,documentoCodigo:e.target.value})} placeholder="Ej. OVOPE-CA-E-253"/></Campo><Campo label="Versión"><Input required min="0.0001" step="0.0001" type="number" value={form.versionNumero} onChange={e=>setForm({...form,versionNumero:e.target.value})}/></Campo><div className="md:col-span-2"><Campo label="Nombre / descripción"><Input required value={form.documentoDescripcionDocumento} onChange={e=>setForm({...form,documentoDescripcionDocumento:e.target.value})}/></Campo></div><Campo label="Inicio de vigencia"><Input type="date" value={form.versionInicioVigencia} onChange={e=>setForm({...form,versionInicioVigencia:e.target.value})}/></Campo><Campo label="N.º páginas"><Input min="1" type="number" value={form.versionNroPaginas} onChange={e=>setForm({...form,versionNroPaginas:e.target.value})}/></Campo></div>
   {crear.isError&&<p className="text-sm text-red-600">{crear.error instanceof Error?crear.error.message:"No se pudo crear la ET."}</p>}
   <div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={()=>setPaso(1)} disabled={crear.isPending}><ArrowLeft/>Atrás</Button><Button type="submit" disabled={crear.isPending}><FilePlus2/>{crear.isPending?"Creando...":"Crear ET"}</Button></div>
  </form>}</CardContent></Card>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div className="mb-5"><h2 className="text-lg font-semibold">Crear nueva sección</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">La sección quedará disponible y se añadirá automáticamente a esta ET.</p></div><div className="space-y-4"><Campo label="Nombre de la sección"><Input autoFocus value={secForm.seccionDescripcion} onChange={e=>setSecForm({...secForm,seccionDescripcion:e.target.value})} placeholder="Ej. Requisitos especiales"/></Campo><Campo label="Tipo de contenido"><select className="h-10 w-full rounded-lg border bg-white px-3 text-sm" value={secForm.idTipoSeccion} onChange={e=>setSecForm({...secForm,idTipoSeccion:e.target.value})}>{(sec.data?.tiposSeccion??[]).map(t=><option key={t.idTipoSeccion} value={t.idTipoSeccion}>{t.descripcion}</option>)}</select></Campo>{crearSec.isError&&<p className="text-sm text-red-600">{crearSec.error instanceof Error?crearSec.error.message:"No se pudo crear la sección."}</p>}</div><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={()=>setModal(false)} disabled={crearSec.isPending}>Cancelar</Button><Button disabled={!secForm.seccionDescripcion.trim()||crearSec.isPending} onClick={()=>crearSec.mutate({seccionDescripcion:secForm.seccionDescripcion.trim(),idTipoSeccion:Number(secForm.idTipoSeccion),usuario:"USUARIO_WEB"})}>{crearSec.isPending?"Creando...":"Crear y añadir"}</Button></div></div></div>}
 </PageContainer>
}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label>}
